apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "voting-lib.fullname" . }}-postgres
  labels:
    {{- include "voting-lib.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStore.kind }}
    name: {{ .Values.externalSecret.secretStore.name }}
  target:
    name: {{ include "voting-lib.postgresSecretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.username }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.password }}
    {{- if .Values.db.enabled }}
    - secretKey: root-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.rootPassword }}
    {{- else if not (((.Values.global).db).connectionSecret) }}
    - secretKey: host
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.host }}
    - secretKey: port
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.port }}
    {{- end }}
{{- if and (not .Values.redis.enabled) (not (((.Values.global).redis).connectionSecret)) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "voting-lib.fullname" . }}-redis
  labels:
    {{- include "voting-lib.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStore.kind }}
    name: {{ .Values.externalSecret.secretStore.name }}
  target:
    name: {{ include "voting-lib.redisSecretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: host
      remoteRef:
        key: {{ .Values.externalSecret.redis.remoteKey }}
        property: {{ .Values.externalSecret.redis.properties.host }}
    - secretKey: port
      remoteRef:
        key: {{ .Values.externalSecret.redis.remoteKey }}
        property: {{ .Values.externalSecret.redis.properties.port }}
{{- end }}
