{{- if .Values.elasticacheSubnets }}
{{- $region := required "region from terraform-values.yaml" .Values.region }}
{{- range .Values.elasticacheSubnets }}
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    crossplane.io/external-name: {{ .id | quote }}
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: {{ $region }}
    availabilityZone: {{ .availabilityZone }}
    tags:
      Name: {{ .name }}
      Tier: redis
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
{{- end }}
{{- end }}
