{{- $rollout := .Values.rollout | default dict }}
{{- if not $rollout.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-lib.fullname" . }}
  labels:
    {{- include "voting-lib.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-lib.selectorLabels" . | nindent 6 }}
  template:
    {{- include "app.podTemplate" . | nindent 4 }}
{{- end }}
