{{- $rollout := .Values.rollout | default dict }}
{{- if $rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "voting-lib.fullname" . }}
  labels:
    {{- include "voting-lib.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ $rollout.revisionHistoryLimit | default 2 }}
  progressDeadlineSeconds: {{ $rollout.progressDeadlineSeconds | default 1800 }}
  selector:
    matchLabels:
      {{- include "voting-lib.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      {{- toYaml $rollout.canary | nindent 6 }}
  template:
    {{- include "app.podTemplate" . | nindent 4 }}
{{- end }}
