{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-lib.fullname" . }}
  labels:
    {{- include "voting-lib.labels" . | nindent 4 }}
  annotations:
    {{- include "voting-lib.syncWave" "3" | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.portName }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voting-lib.selectorLabels" . | nindent 4 }}
{{- end }}
