{{- if and .Values.httpRoute.enabled .Values.service.enabled (eq (include "voting-lib.gatewayProvider" .) "aws") }}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ include "voting-lib.fullname" . }}{{ if .Values.stickiness.enabled }}-sticky{{ end }}
  labels:
    {{- include "voting-lib.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetReference:
    group: ""
    kind: Service
    name: {{ include "voting-lib.fullname" . }}
  defaultConfiguration:
    targetType: {{ .Values.stickiness.aws.targetType }}
    {{- if .Values.stickiness.enabled }}
    targetGroupAttributes:
      - key: stickiness.enabled
        value: "true"
      - key: stickiness.type
        value: lb_cookie
      - key: stickiness.lb_cookie.duration_seconds
        value: {{ .Values.stickiness.aws.durationSeconds | quote }}
    {{- end }}
{{- end }}
